spring:
  #application:
    #name: flight-proxy-service 
  #profiles: default

server:
  port: 7102

eureka:
  instance:
    hostname: localhost
    port: 7100
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

zuul:
  routes:
    flight-login-service:
      path: /flight-login/**
      serviceId: flight-login-service
    flight-registration-service:
      path: /flight-registration/**
      serviceId: flight-registration-service
    flight-search-service:
      path: /flight-search/**
      serviceId: flight-search-service
    flight-book-service:
      path: /flight-book/**
      serviceId: flight-book-service

logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    com.gokoders.proxy: DEBUG
  file:  /tmp/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


#  cloud:
#    config:
#      uri: http://localhost:9090