spring:
  #application:
    #name: flight-book-service
  #profiles: default
  datasource:
    url: jdbc:h2:mem:gokodersflightbook;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
    allowed:
      resources: /h2-console/**
    security:
      basic:
        enabled: true
        authorize-mode: NONE
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      indent-output: true

server:
  port: 7106

eureka:
  instance:
    hostname: localhost
    port: 7100
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000

logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    com.gokoders.book: DEBUG
  file:  /tmp/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  packagesToScan: com.gokoders.book

#  cloud:
#    config:
#      uri: http://localhost:9090